
/**
 * @typedef {String | Number} EncounterType
 */
export const ENCOUNTER_TYPES = {
  GENERIC: 'GENERIC-ENCOUNTER-TYPE',
  STREET: 'STREET-ENCOUNTER-TYPE',
  LAWN: 'LAWN-ENCOUNTER-TYPE',
  HOUSE: 'HOUSE-ENCOUNTER-TYPE',
  SPECIAL: 'SPECIAL-ENCOUNTER-TYPE',
  DEAD_END: 'DEAD_END-ENCOUNTER-TYPE',
  CUL_DE_SAC: 'CUL_DE_SAC-ENCOUNTER-TYPE',
};

export default ENCOUNTER_TYPES;
