import convertObjectToArray from 'utilities.shared/convertObjectToArray';

/**
 * @typedef {String} TriggerId
 */

export const ENCOUNTER_TRIGGER_ID = {
  CANDY: {
    ADD: 'ENCOUNTER_TRIGGER_ID.CANDY.ADD',
    SUBTRACT: 'ENCOUNTER_TRIGGER_ID.CANDY.SUBTRACT',
  },

  HEALTH: {
    ADD: 'ENCOUNTER_TRIGGER_ID.HEALTH.ADD',
    SUBTRACT: 'ENCOUNTER_TRIGGER_ID.HEALTH.SUBTRACT',
  },

  MOVEMENT: {
    ADD: 'ENCOUNTER_TRIGGER_ID.MOVEMENT.ADD',
    SUBTRACT: 'ENCOUNTER_TRIGGER_ID.MOVEMENT.SUBTRACT',
  },

  SANITY: {
    ADD: 'ENCOUNTER_TRIGGER_ID.SANITY.ADD',
    SUBTRACT: 'ENCOUNTER_TRIGGER_ID.SANITY.SUBTRACT',
  },

  VISION: {
    ADD: 'ENCOUNTER_TRIGGER_ID.VISION.ADD',
    SUBTRACT: 'ENCOUNTER_TRIGGER_ID.VISION.SUBTRACT',
  },

  LUCK: {
    ADD: 'ENCOUNTER_TRIGGER_ID.LUCK.ADD',
    SUBTRACT: 'ENCOUNTER_TRIGGER_ID.LUCK.SUBTRACT',
  },

  GREED: {
    ADD: 'ENCOUNTER_TRIGGER_ID.GREED.ADD',
    SUBTRACT: 'ENCOUNTER_TRIGGER_ID.GREED.SUBTRACT',
  },

  CHANGE_POSITION: 'ENCOUNTER_TRIGGER_ID.CHANGE_POSITION',
};
export const ENCOUNTER_TRIGGER_ID_LIST = convertObjectToArray(ENCOUNTER_TRIGGER_ID);
