/**
 * @typedef {String} SocketEvent - event names
 */
export const SOCKET_EVENTS = {
  LOBBY: {
    UPDATE: 'SOCKET_EVENTS.LOBBY.UPDATE',
    START: 'SOCKET_EVENTS.LOBBY.START',
    JOIN: 'SOCKET_EVENTS.LOBBY.JOIN',
  },

  GAME: {
    ACTION: 'SOCKET_EVENTS.GAME.ACTION',
    ENCOUNTER: 'SOCKET_EVENTS.GAME.ENCOUNTER',
    END: 'SOCKET_EVENTS.GAME.END',
  },

  UPDATE: {
    CLIENT: 'SOCKET_EVENTS.UPDATE.CLIENT',
    GAME: 'SOCKET_EVENTS.UPDATE.GAME',
    MY_CHARACTER: 'SOCKET_EVENTS.UPDATE.MY_CHARACTER',
  },

  DEBUG: {
    LOG: 'SOCKET_EVENTS.DEBUG.LOG',
    TILE_EDITOR: 'SOCKET_EVENTS.DEBUG.TILE_EDITOR',
    MAP_HISTORY: 'SOCKET_EVENTS.DEBUG.MAP_HISTORY',
    RESTART_GAME: 'SOCKET_EVENTS.DEBUG.RESTART_GAME',
  }
};
