/**
 * @typedef {String} SocketEvent - event names
 */
export const SOCKET_EVENTS = {
  LOBBY: {
    UPDATE: 'SOCKET_EVENTS.LOBBY.UPDATE',
    START: 'SOCKET_EVENTS.LOBBY.START',
    JOIN: 'SOCKET_EVENTS.LOBBY.JOIN',
  },

  GAME: {
    ACTION: 'SOCKET_EVENTS.GAME.ACTION',
    ENCOUNTER: 'SOCKET_EVENTS.GAME.ENCOUNTER',
  },

  UPDATE: {
    CLIENT: 'SOCKET_EVENTS.UPDATE.CLIENT',
    GAME: 'SOCKET_EVENTS.UPDATE.GAME',
    MY_CHARACTER: 'SOCKET_EVENTS.UPDATE.MY_CHARACTER',
  }
};
