import convertObjectToArray from 'utilities.shared/convertObjectToArray';

/**
 * hmm, the idea is that when searching for a thing that is custom made
 *  you would search by tags
 */

/**
 * @typedef {String} TagId
 */
export const TAG_ID = {
  TYPE: {
    DEBUG: 'TAG_ID.TYPE.DEBUG',
    ENCOUNTER: 'TAG_ID.TYPE.ENCOUNTER',
    HOUSE: 'TAG_ID.TYPE.HOUSE',
    ITEM: 'TAG_ID.TYPE.ITEM',
  },

  TILE_TYPE: {
    SIDEWALK: 'TAG_ID.TILE_TYPE.SIDEWALK',
    LIT_SIDEWALK: 'TAG_ID.TILE_TYPE.LIT_SIDEWALK',
    ROAD: 'TAG_ID.TILE_TYPE.ROAD',
    LIT_ROAD: 'TAG_ID.TILE_TYPE.LIT_ROAD',
    SWAMP: 'TAG_ID.TILE_TYPE.SWAMP',
    LIT_SWAMP: 'TAG_ID.TILE_TYPE.LIT_SWAMP',
    PLANKS: 'TAG_ID.TILE_TYPE.PLANKS',
    LIT_PLANKS: 'TAG_ID.TILE_TYPE.LIT_SIDEWALK',
    WOODS: 'TAG_ID.TILE_TYPE.WOODS',
    LIT_WOODS: 'TAG_ID.TILE_TYPE.LIT_WOODS',
    WOODS_TWO: 'TAG_ID.TILE_TYPE.WOODS_TWO',
    LIT_WOODS_TWO: 'TAG_ID.TILE_TYPE.LIT_WOODS_TWO',
    GRASS: 'TAG_ID.TILE_TYPE.GRASS',
    LIT_GRASS: 'TAG_ID.TILE_TYPE.LIT_GRASS',
    PATH: 'TAG_ID.TILE_TYPE.PATH',
    LIT_PATH: 'TAG_ID.TILE_TYPE.LIT_PATH',
  },

  DESCRIPTORS: {
    GIVES_ITEM: 'TAG_ID.DESCRIPTORS.GIVES_ITEM',
    ADDS_CANDY: 'TAG_ID.DESCRIPTORS.ADDS_CANDY',
    LOSES_CANDY: 'TAG_ID.DESCRIPTORS.LOSES_CANDY',
    ADDS_HEALTH: 'TAG_ID.DESCRIPTORS.ADDS_HEALTH',
    LOSES_HEALTH: 'TAG_ID.DESCRIPTORS.LOSES_HEALTH',
    ADDS_SANITY: 'TAG_ID.DESCRIPTORS.ADDS_SANITY',
    LOSES_SANITY: 'TAG_ID.DESCRIPTORS.LOSES_SANITY',
  },

  RARITY: {
    COMMON: 'TAG_ID.RARITY.COMMON',
    UNCOMMON: 'TAG_ID.RARITY.UNCOMMON',
    RARE: 'TAG_ID.RARITY.RARE',
  },
};
/**
 * caches an array of the all the TagIds
 */
export const TAG_ID_LIST = convertObjectToArray(TAG_ID);
/** @type {Array} */
export const TYPES_TAG_ID_LIST = [
  TAG_ID.TYPE.DEBUG,
  TAG_ID.TYPE.ENCOUNTER,
  TAG_ID.TYPE.HOUSE,
  TAG_ID.TYPE.ITEM,
];
/** @type {Array} */
export const TILE_TYPE_TAG_ID_LIST = [
  TAG_ID.TILE_TYPE.SIDEWALK,
  TAG_ID.TILE_TYPE.LIT_SIDEWALK,
  TAG_ID.TILE_TYPE.ROAD,
  TAG_ID.TILE_TYPE.LIT_ROAD,
  TAG_ID.TILE_TYPE.SWAMP,
  TAG_ID.TILE_TYPE.LIT_SWAMP,
  TAG_ID.TILE_TYPE.PLANKS,
  TAG_ID.TILE_TYPE.LIT_PLANKS,
  TAG_ID.TILE_TYPE.WOODS,
  TAG_ID.TILE_TYPE.LIT_WOODS,
  TAG_ID.TILE_TYPE.WOODS_TWO,
  TAG_ID.TILE_TYPE.LIT_WOODS_TWO,
  TAG_ID.TILE_TYPE.GRASS,
  TAG_ID.TILE_TYPE.LIT_GRASS,
  TAG_ID.TILE_TYPE.PATH,
  TAG_ID.TILE_TYPE.LIT_PATH,
];
/** @type {Array} */
export const DESCRIPTORS_TAG_ID_LIST = [
  TAG_ID.DESCRIPTORS.GIVES_ITEM,
  TAG_ID.DESCRIPTORS.ADDS_CANDY,
  TAG_ID.DESCRIPTORS.LOSES_CANDY,
  TAG_ID.DESCRIPTORS.ADDS_HEALTH,
  TAG_ID.DESCRIPTORS.LOSES_HEALTH,
  TAG_ID.DESCRIPTORS.ADDS_SANITY,
  TAG_ID.DESCRIPTORS.LOSES_SANITY,
];
/** @type {Array} */
export const RARITY_TAG_ID_LIST = [
  TAG_ID.RARITY.COMMON,
  TAG_ID.RARITY.UNCOMMON,
  TAG_ID.RARITY.RARE,
];
