/**
 * @typedef {Number} TileType
 */
export const TILE_TYPES = {
  null: null,
  EMPTY: 0,

  // walkable tiles
  SIDEWALK: 5,
  LIT_SIDEWALK: 6,

  ROAD: 7,
  LIT_ROAD: 8,

  SWAMP: 9,
  LIT_SWAMP: 10,

  PLANKS: 11,
  PLANKS_TWO: 12,

  WOODS: 13,
  LIT_WOODS: 14,
  WOODS_TWO: 15,
  LIT_WOODS_TWO: 16,

  DIRT: 40, // (dirt)
  LIT_DIRT: 41,

  PATH: 42, // (dirt)
  LIT_PATH: 43,

  // unwalkable tiles
  WATER: 30,
  LIT_WATER: 31,

  DIRTY_WATER: 32,
  LIT_DIRTY_WATER: 33,

  FOREST: 34,
  LIT_FOREST: 35,
  FOREST_TWO: 36,
  LIT_FOREST_TWO: 37,

  GRASS: 38,
  LIT_GRASS: 39,

  // ?
  HOUSE: 51,
  ENCOUNTER: 52,
  SPECIAL: 53,

  // decorations
  BUSH: 81,

  TREE_ONE: 82,
  TREE_TWO: 83,
  TREE_THREE: 84,

  SPOOKY_TREE_ONE: 85,
  SPOOKY_TREE_TWO: 86,
  SPOOKY_TREE_THREE: 87,

  LAMPPOST_ONE: 88,
  LAMPPOST_TWO: 89,

  GRAVE_ONE: 90,
  GRAVE_TWO: 91,

  // DEBUG
  DEBUG_RED: 101,
  DEBUG_ORANGE: 102,
  DEBUG_YELLOW: 103,
  DEBUG_GREEN: 104,
  DEBUG_BLUE: 105,
  DEBUG_INDIGO: 106,
  DEBUG_VIOLET: 107,
  DEBUG_BLACK: 110,
  DEBUG_WHITE: 111,

  DEBUG_WALL_RED: 201,
  DEBUG_WALL_ORANGE: 202,
  DEBUG_WALL_YELLOW: 203,
  DEBUG_WALL_GREEN: 204,
  DEBUG_WALL_BLUE: 205,
  DEBUG_WALL_INDIGO: 206,
  DEBUG_WALL_VIOLET: 207,
  DEBUG_WALL_BLACK: 210,
  DEBUG_WALL_WHITE: 211,
};
/**
 * this is the reverse of the above Key/Value map,
 *  don't depend on this
 * @example { 0: 'EMPTY', 1: 'PATH' }
 */
export const TILE_TYPES_NAME = (() => {
  const result = {};
  Object.keys(TILE_TYPES).forEach((key) => {
    result[TILE_TYPES[key]] = key;
  });
  return result;
})();
/**
 * @type {Array<TileType>}
 */
export const WALKABLE_TILE_TYPES = [
  TILE_TYPES.DIRT,
  TILE_TYPES.LIT_DIRT,
  TILE_TYPES.SIDEWALK,
  TILE_TYPES.LIT_SIDEWALK,
  TILE_TYPES.ROAD,
  TILE_TYPES.LIT_ROAD,
  TILE_TYPES.SWAMP,
  TILE_TYPES.LIT_SWAMP,
  TILE_TYPES.PLANKS,
  TILE_TYPES.PLANKS_TWO,
  TILE_TYPES.WOODS,
  TILE_TYPES.LIT_WOODS,
  TILE_TYPES.WOODS_TWO,
  TILE_TYPES.LIT_WOODS_TWO,
  TILE_TYPES.GRASS,
  TILE_TYPES.LIT_GRASS,
  TILE_TYPES.PATH,
  TILE_TYPES.LIT_PATH,

  TILE_TYPES.HOUSE,
  TILE_TYPES.ENCOUNTER,
  TILE_TYPES.SPECIAL,

  TILE_TYPES.DEBUG_RED,
  TILE_TYPES.DEBUG_ORANGE,
  TILE_TYPES.DEBUG_YELLOW,
  TILE_TYPES.DEBUG_GREEN,
  TILE_TYPES.DEBUG_BLUE,
  TILE_TYPES.DEBUG_INDIGO,
  TILE_TYPES.DEBUG_VIOLET,
  TILE_TYPES.DEBUG_BLACK,
  TILE_TYPES.DEBUG_WHITE,
];
/**
 * @type {Array<TileType>}
 */
export const LIT_TILE_TYPES = [
  TILE_TYPES.LIT_PATH,
  TILE_TYPES.LIT_GRASS,
  TILE_TYPES.LIT_SIDEWALK,
  TILE_TYPES.LIT_ROAD,
  TILE_TYPES.LIT_SWAMP,
  TILE_TYPES.LIT_WOODS,
  TILE_TYPES.LIT_WOODS_TWO,

  TILE_TYPES.LAMPPOST_ONE,
  TILE_TYPES.LAMPPOST_TWO,
];
/**
 * @type {Array<TileType>}
 */
export const WALL_TILE_TYPE_LIST = [
  TILE_TYPES.EMPTY,
  TILE_TYPES.TREE_ONE,
  TILE_TYPES.TREE_TWO,
  TILE_TYPES.TREE_THREE,

  TILE_TYPES.DEBUG_WALL_RED,
  TILE_TYPES.DEBUG_WALL_ORANGE,
  TILE_TYPES.DEBUG_WALL_YELLOW,
  TILE_TYPES.DEBUG_WALL_GREEN,
  TILE_TYPES.DEBUG_WALL_BLUE,
  TILE_TYPES.DEBUG_WALL_INDIGO,
  TILE_TYPES.DEBUG_WALL_VIOLET,
  TILE_TYPES.DEBUG_WALL_BLACK,
  TILE_TYPES.DEBUG_WALL_WHITE,
];
/** @type {Array<TileType>} */
export const RAINBOW_DEBUG_TILES = [
  TILE_TYPES.DEBUG_RED,
  TILE_TYPES.DEBUG_ORANGE,
  TILE_TYPES.DEBUG_YELLOW,
  TILE_TYPES.DEBUG_GREEN,
  TILE_TYPES.DEBUG_BLUE,
  TILE_TYPES.DEBUG_INDIGO,
  TILE_TYPES.DEBUG_VIOLET,
];
