import * as THREE from 'three';

export const WEB_GL_RENDERER = {
  ALPHA: true,
  ANTIALIAS: true
}

const DISTANCE = 500;
const CAMERA_ROTATION_X = 50*Math.PI/180;
const CAMERA_ROTATION_Y = 20*Math.PI/180;
const CAMERA_ROTATION_Z = 10*Math.PI/180;
const INITIAL_CAMERA_POSITION_Y = -Math.tan(CAMERA_ROTATION_X)*DISTANCE;
const INITIAL_CAMERA_POSITION_X = Math.tan(CAMERA_ROTATION_Y)*Math.sqrt(DISTANCE**2 + INITIAL_CAMERA_POSITION_Y**2);
export const CAMERA = {
  DISTANCE: DISTANCE,
  CAMERA_ROTATION_X: CAMERA_ROTATION_X,
  CAMERA_ROTATION_Y: CAMERA_ROTATION_Y,
  CAMERA_ROTATION_Z: CAMERA_ROTATION_Z,
  INITIAL_CAMERA_POSITION_Y: INITIAL_CAMERA_POSITION_Y,
  INITIAL_CAMERA_POSITION_X: INITIAL_CAMERA_POSITION_X,
};
export const SCENE = {
  ZOOM: 2,
  ORIGIN_POS: { x: 0, y: 0 },
  BACKGROUND_COLOR: 0xffffff
}
export const RENDERER = {
  ALPHA: WEB_GL_RENDERER.ALPHA,
  ANTIALIAS: WEB_GL_RENDERER.ANTIALIAS,
  SHADOW_MAP_ENABLED: true,
  SHADOW_MAP_TYPE: THREE.PCFSoftShadowMap,
  SIZE_X: window.innerWidth,
  SIZE_Y: window.innerHeight,
}
export const HEMI_LIGHT = {
  SKY_COLOR: 0xffffff,
  GROUND_COLOR: 0xffffff,
  INTESITY: 0.6,
}
const SHADOW_CAMERA_VALUE = 500;
export const DIR_LIGHT = {
  COLOR: 0xffffff,
  INTESITY: 0.6,
  POSITION: new THREE.Vector3(-100, -100, 200),
  CAST_SHADOW: true,
  SHADOW_MAP_SIZE_WIDTH: 2048,
  SHADOW_MAP_SIZE_HEIGHT: 2048,
  SHADOW_CAMERA_VALUE: SHADOW_CAMERA_VALUE,
  SHADOW_CAMERA_LEFT: - SHADOW_CAMERA_VALUE,
  SHADOW_CAMERA_RIGHT: SHADOW_CAMERA_VALUE,
  SHADOW_CAMERA_TOP: SHADOW_CAMERA_VALUE,
  SHADOW_CAMERA_BOTTOM: - SHADOW_CAMERA_VALUE,
}
export const BACK_LIGHT = {
  COLOR: 0x000000,
  INTESITY: 0.4,
  POSITION: new THREE.Vector3(200, 200, 50),
  CAST_SHADOW: true,
}
// Game
export const TILES = {
  TILE_SIZE: 42,
  TILE_TRAIL_SIZE: 4,
  TILE_HEIGHT: 3,
  TILE_TYPES: [4], //[1, 2, 3, 4];
  POSITION_WIDTH: 42,
  COLOR: 0xdddddd,
  FLAT_SHADING: true,
  CAST_SHADOW: true,
  RECEIVE_SHADOW: true,
  POSITION_HEIGHT: 0
}
export const TILES_SIDES = {
  FORWARD: 0,
  RIGHT: 1,
  BACKWARD: 2,
  LEFT: 3
}
export const TILE_DIRECTIONS = {
  FORWARD: 'FORWARD',
  RIGHT: 'LEFT',
  BACKWARD: 'BACKWARD',
  LEFT: 'RIGHT'
}
export const TILE_REVERSE_DIRECTIONS = {
  FORWARD: 'BACKWARD',
  RIGHT: 'LEFT',
  BACKWARD: 'FORWARD',
  LEFT: 'RIGHT'
}
export const PLAYER = {
  SIZE: 15,
  COLOR: 0xeeeeee,
  FLAT_SHADING: true,
  CAST_SHADOW: true,
  RECEIVE_SHADOW: true,
  POSITION_HEIGHT: 6*SCENE.ZOOM
}
export const ANIMATION = {
  STEP_TIME: 200,
  JUMP: false,
}
