import {STAT_ID} from 'constants.shared/statIds';
import {TARGET_ID} from 'constants.shared/targetIds';

/** @type {Object} */
const TARGET_TO_STAT_MAP = {
  [TARGET_ID.CHARACTER.CANDIES]: STAT_ID.CANDIES,
  [TARGET_ID.CHARACTER.HEALTH]: STAT_ID.HEALTH,
  [TARGET_ID.CHARACTER.GREED]: STAT_ID.GREED,
  [TARGET_ID.CHARACTER.LUCK]: STAT_ID.LUCK,
  [TARGET_ID.CHARACTER.MOVEMENT]: STAT_ID.MOVEMENT,
  [TARGET_ID.CHARACTER.TRICKY]: STAT_ID.TRICKY,
  [TARGET_ID.CHARACTER.TREATY]: STAT_ID.TREATY,
  [TARGET_ID.CHARACTER.SANITY]: STAT_ID.SANITY,
  [TARGET_ID.CHARACTER.VISION]: STAT_ID.VISION,

  [TARGET_ID.CHARACTER.NEIGHBORS_FAVOR]: STAT_ID.NEIGHBORS_FAVOR,
};
/**
 * @param {TargetId} targetId
 * @returns {StatId}
 */
export function convertTargetToStat(targetId) {
  return TARGET_TO_STAT_MAP[targetId];
}
